simulated_sensor_config:
  prefilter:
    allowed_semantic_tags:
      - Pedestrian
      - Vehicles
    max_distance_meters: 100
  detection_threshold_scaling_formula:
    nominal_hitpoint_detection_ratio_threshold: 0.6
    hitpoint_detection_ratio_threshold_per_meter_change_rate: -0.0033
    and_scaling_parameters_for_the_adjustable_threshold:
      dropoff_rate: 0.01
default_semantic_lidar_sensor_config:
  lower_fov: -80.0
  upper_fov: 30.0
  range: 100.0
  channels: 60
  points_per_second: 10000
  rotation_frequency: 10.0
  sensor_tick: 0.1
