simulated_sensor:
  prefilter:
    allowed_type_id_list:
      - vehicle.*
      - .*pedestrian.*
    max_distance_meters: 1000
  detection_threshold_scaling_formula:
    nominal_hitpoint_detection_ratio_threshold: 0.6
    hitpoint_detection_ratio_threshold_per_meter_change_rate: -0.0033
    adjustable_threshold_scaling_parameters:
      dropoff_rate: 0.01
  geometry_reassociation:
    sample_count: 9
    geometry_association_max_distance_threshold: 2.0
    trailing_id_associations_count: 2
  use_sensor_centric_frame: True
lidar_sensor:
  lower_fov: -10.0
  upper_fov: 15.0
  channels: 1024
  range: 100.0
  rotation_period: 0.02
  points_per_second: 1000000
